- name: Player’s Handbook
  source: PHB
- name: Sword Coast Adveturer’s Guide
  source: SCAG
- name: Elemental Evil Player’s Companion
  source: EE
- name: Xanathar’s Guide to Everything
  source: XGE
- name: Tasha’s Cauldron of Everything
  source: TCE
- name: Fizban’s Treasury of Dragons
  source: FTD
- name: "Strixhaven: A Curriculum of Chaos"
  source: SCC
- name: "Explorer’s Guide to Wildemount"
  source: EGW
- name: "Acquisitions Incorporated"
  source: AI
- name: "Astral Adventurer’s Guide"
  source: AAG
- name: "Player’s Handbook 2024"
  source: PHB 2024
- name: "Exploring Eberron (2024)"
  source: Exploring Eberron 2024
- name: "Frontiers of Eberron (2024)"
  source: Frontiers 2024
- name: "Forge of the Artificer (2024)"
  source: Forge 2024
- name: "Heroes of Faerûn (2024)"
  source: Heroes of Faerun 2024
